### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.util.SortedMap kotlin.collections.MapsKt.sortedMapOf(java.util.Comparator, kotlin.Pair[])'

### ISSUE THREAD

**Issue by gjain-sag** [akkinoc/logback-access-spring-boot-starter#137]
### Environment

* **Version of this library used**:3.2.2
* **Version of Java used**:1.8

**Comment by akkinoc** [comment]
Can you tell me the version of your Spring Boot (or Kotlin)?

logback-access-spring-boot-starter v3.1/v3.2 requires Spring Boot v2.6 (Kotlin v1.6).
Please upgrade to Spring Boot v2.6 (Kotlin v1.6).

Note: `java.util.SortedMap kotlin.collections.MapsKt.sortedMapOf(java.util.Comparator, kotlin.Pair[])` is a method introduced in Kotlin v1.4.

**Comment by gjain-sag** [comment]
Spring boot version : 2.2.7.RELEASE
I can't upgrade my spring boot as there are other dependencies, do we have an supported version for logback-starter against against spring boot 2.2.7RELEASE

**Comment by akkinoc** [comment]
It may work with logback-access-spring-boot-starter v2.11.0.
https://github.com/akkinoc/logback-access-spring-boot-starter/tree/v2.11.0

However, please note that I have no plans to update other than the latest version.

**Comment by akkinoc** [comment]
This issue is inactive, so I close it.
If you still have problems, please open a new issue.
