### ISSUE TITLE
Support Spring Boot 3

### ISSUE THREAD

**Issue by theotherp** [akkinoc/logback-access-spring-boot-starter#279]
Any chances of getting this to work with SB3? Thanks!

**Comment by akkinoc** [comment]
Thanks for report.
I would like to support it in future versions!

**Comment by raimi** [comment]
I would also like to use this starter with Spring Boot 3. Thanks to Pirayya for the PR!

**Comment by raimi** [comment]
Thanks a ton! We will check it out within the next few days (or weeks :))...

**Comment by akkinoc** [comment]
Thank you for waiting. I have released v4 🎉

**Comment by JoeHegarty** [comment]
Awesome. 
Not seeing 4.0.0 in Maven central yet, are you planning on publishing?

**Comment by akkinoc** [comment]
It seems there was a mistake in the release process, I'm sorry.
I have re-released it, so please check again in a few hours.
Thank you for your feedback!

**Comment by JoeHegarty** [comment]
Working perfectly for me now, thanks!

**Comment by akkinoc** [comment]
@JoeHegarty Thank you for your support! 🌟 💖

**Comment by raimi** [comment]
Same here. Works. Thanks a ton!
