### ISSUE TITLE
add support for request and response headers fields

### ISSUE THREAD

**Issue by regevbr** [akkinoc/logback-access-spring-boot-starter#36]
i.e.
```
<SpringResponseHeader>
   <fieldName>X-B3-TraceId</fieldName>
   <header>TraceId</header>
</SpringResponseHeader>
```

**Comment by akihyro** [comment]
I think that this will be helpful.

* https://logback.qos.ch/access.html#configuration
* https://logback.qos.ch/manual/layouts.html#AccessPatternLayout

If you use `PatternLayout`, you can use `%i{header}`, `%header{header}`, `%responseHeader{header}`.

**Comment by akkinoc** [comment]
This issue is inactive, so I close it.
If you still have problems, please open a new issue.
