### ISSUE TITLE
add support for json logging

### ISSUE THREAD

**Issue by regevbr** [akkinoc/logback-access-spring-boot-starter#37]
In the case we want to send the access logs to kibana etc. we need the logs to be in JSON format.

**Comment by akihyro** [comment]
I think that formatting the output is the work of Logback's Appenders/Encoders/Layouts.
So, I do not have plans to support it.
Please combine another libraries or your own implementation.

Logback's Appender can be set in "logback-access.xml".
For example:

```xml
<configuration>
    <appender name="JSON" class="com.example.YourJsonFormatAppender">
        ...
    </appender>
    <appender-ref ref="JSON" />
</configuration>
```

**Comment by abatkin** [comment]
We use [logstash-logback-encoder](https://github.com/logstash/logstash-logback-encoder) (specifically `AccessEventCompositeJsonEncoder`) together with this project and it works great.

**Comment by xrom888** [comment]
hi @abatkin! Could you please attach access config here (with AccessEventCompositeJsonEncoder), that works for you?

**Comment by Athas1980** [comment]
@xrom888 I couldn't get AccessEventCompositeJsonEncoder to work

but this logs in json
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
		<encoder class="net.logstash.logback.encoder.LogstashAccessEncoder" />
	</appender>
	<appender-ref ref="CONSOLE" />
</configuration>
```

Log example
```
{"@timestamp":"2020-09-08T14:38:08.455+01:00","@version":"1","message":"0:0:0:0:0:0:0:1 - org.springframework.security.oauth2.jwt.Jwt@be89024 [2020-09-08T14:38:08.455+01:00] \"POST /evaluate/merchant/12346/ HTTP/1.1\" 500 11844","method":"POST","protocol":"HTTP/1.1","status_code":500,"requested_url":"POST /evaluate/merchant/12346/ HTTP/1.1","requested_uri":"/evaluate/merchant/12346/","remote_host":"0:0:0:0:0:0:0:1","remote_user":"org.springframework.security.oauth2.jwt.Jwt@be89024","content_length":11844,"elapsed_time":281}```

**Comment by akkinoc** [comment]
This issue is inactive, so I close it.
If you still have problems, please open a new issue.
