### ISSUE TITLE
Jetty 12 Compatibility (Spring Boot 3.2.x)

### ISSUE THREAD

**Issue by DarkAtra** [akkinoc/logback-access-spring-boot-starter#374]
## Describe the problem you'd like to have solved

[Spring Boot 3.2 just released](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes) and [introduced support for Jetty 12](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#jetty-12). There were quite a few changes introduced in Jetty 12 that render this starter unusable with Spring Boot 3.2.x and the `spring-boot-starter-jetty` starter.

I guess there's not much you could do right now as compatibility for Jetty 12 likely also [requires changes to logback-access](https://github.com/qos-ch/logback/issues/719) itself.

Would it make sense to release a new version that updates the parent to Spring Boot 3.2.0 and explicitly states incompatibility with Jetty?

**Comment by daniel-kr** [comment]
I recognized that the [mentioned underlying issue of the logback library](https://github.com/qos-ch/logback/issues/719) is already solved. Are there any plans to make the spring-boot-starter compatible with SB 3.2/Jetty 12 as well?

**Comment by DarkAtra** [comment]
there's an open PR that adds jetty 12 support: https://github.com/akkinoc/logback-access-spring-boot-starter/pull/407

**Comment by akkinoc** [comment]
v4.2.0 has been released! It will be available in the Maven Central repository soon.
