### ISSUE TITLE
Add support for async appenders

### ISSUE THREAD

**Issue by regevbr** [akkinoc/logback-access-spring-boot-starter#38]
In the case we don't want the logs to hold the execution threads...

Easy as adding:
```
public class AsyncAppender extends AsyncAppenderBase<IAccessEvent> {

    private static final int CLIENT_ERROR_START = 400;
    private static final int CLIENT_ERROR_END = 599;

    @Override
    protected boolean isDiscardable(IAccessEvent event) {
        int status = event.getStatusCode();
        return status < CLIENT_ERROR_START || status > CLIENT_ERROR_END;
    }

    @Override
    protected void preprocess(IAccessEvent eventObject) {
        eventObject.prepareForDeferredProcessing();
    }


}
```

And in the xml file:
```
  <appender name="ASYNC_ACCESS" class="com.intel.swiss.micro.framework.log.logback.AsyncAppender">
    <appender-ref ref="FILE_ACCESS"/>
  </appender>
```

**Comment by dirklu** [comment]
thank you!!!!

**Comment by dirklu** [comment]
> In the case we don't want the logs to hold the execution threads...
> 
> Easy as adding:
> 
> ```
> public class AsyncAppender extends AsyncAppenderBase<IAccessEvent> {
> 
>     private static final int CLIENT_ERROR_START = 400;
>     private static final int CLIENT_ERROR_END = 599;
> 
>     @Override
>     protected boolean isDiscardable(IAccessEvent event) {
>         int status = event.getStatusCode();
>         return status < CLIENT_ERROR_START || status > CLIENT_ERROR_END;
>     }
> 
>     @Override
>     protected void preprocess(IAccessEvent eventObject) {
>         eventObject.prepareForDeferredProcessing();
>     }
> 
> 
> }
> ```
> And in the xml file:
> 
> ```
>   <appender name="ASYNC_ACCESS" class="com.intel.swiss.micro.framework.log.logback.AsyncAppender">
>     <appender-ref ref="FILE_ACCESS"/>
>   </appender>
> ```
thank you

**Comment by swcumt** [comment]
grateful

**Comment by akkinoc** [comment]
Sorry for the late reply.
If you still have problems, please open a new issue.
