### ISSUE TITLE
Using on Willdfly / JBoss

### ISSUE THREAD

**Issue by floresek** [akkinoc/logback-access-spring-boot-starter#39]
Hi,

is it possible to use yuor solution on Wildfly (10) / JBoss (EAP 7)?
If yes - could you write short "how to" or add simple project, please?

Cheers
Mariusz

**Comment by akihyro** [comment]
"logback-access-spring-boot-starter" only supports Tomcat, Jetty, Undertow.
Sorry, I do not have enough knowledge of Willdfly and JBoss, so it is difficult to support...


Thanks.

**Comment by akkinoc** [comment]
This issue is inactive, so I close it.
If you still have problems, please open a new issue.
