### ISSUE TITLE
Errors log wrong path and uri for undertow.

### ISSUE THREAD

**Issue by jeacott1** [akkinoc/logback-access-spring-boot-starter#45]
I have a spring boot 1.5.8 / undertow project with spring security configured and a standard spring error handler
```
@RestController
public class DefaultErrorController implements ErrorController {
	private static final String PATH = "/error";
...
```
for access logs,  
using a spring @Configuration to get access logs
```
@Bean
    public EmbeddedServletContainerFactory servletContainer() {
        UndertowEmbeddedServletContainerFactory factory = new UndertowEmbeddedServletContainerFactory();
        factory.addDeploymentInfoCustomizers(new UndertowDeploymentInfoCustomizer() {
            @Override
            public void customize(DeploymentInfo deploy) {
      
                deploy.addInitialHandlerChainWrapper(new HandlerWrapper() {
                    @Override
                    public HttpHandler wrap(HttpHandler handler) {
                        return new AccessLogHandler(handler, new JBossLoggingAccessLogReceiver(), "combined", Undertow.class.getClassLoader());
                    }
                });
            }
        });

        return factory;
    }
```
and then calling an endpoint with
curl http://localhost:8080/someBrokenPath

I get an access log that looks like this:

2018-06-05 12:23:39.466  INFO 10156 --- [  XNIO-2 task-1] io.undertow.accesslog                    : 0:0:0:0:0:0:0:1 - - [05/Jun/2018:12:23:39 +0930] "GET /someBrokenPath HTTP/1.1" 401 106 "-" "curl/7.59.0"

however
when I configure logback-access-spring-boot-starter with 

```
<configuration>
    <statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener" />
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
         <encoder>
            <pattern>common</pattern>
        </encoder>
    </appender>

    <appender-ref ref="CONSOLE" />

</configuration>
```

I get:
0:0:0:0:0:0:0:1 - - [05/Jun/2018:14:48:29 +0930] "GET /error HTTP/1.1" 401 106

I know I can manually modify the pattern to fix the missing status, threadname etc,

but what seems really broken is the path says "/error" and not "/someBrokenPath"

update: 
actually the presence of a custom ErrorController  makes no difference. but excluding the spring boot whitelabel error handler resolves the issue:
@SpringBootApplication(exclude = {ErrorMvcAutoConfiguration.class}

after that I get ... [2018-06-06T12:52:44.735+09:30] \"GET /someBrokenPath HTTP/1.1\" 401 71" ...

unfortunately I do need to customise this and I'm not seeing how I can without losing useful logs.

**Comment by jeacott1** [comment]
for those who might at least like this to work since activity here appears nil. here's a hacky fix. https://github.com/akihyro/logback-access-spring-boot-starter/pull/46

**Comment by akihyro** [comment]
Thanks for contributing!
I will check pull requests.
I would like to have some time to consider.

**Comment by a8t3r** [comment]
By default, undertow request dispatcher [sets an attribute](https://github.com/undertow-io/undertow/blob/51231e4557fe2cc92454f8ec4c6c7a83db554bad/servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java#L449) with original request uri.

I wrote a test with default spring ErrorController and that attribute appears.
So a better decision will override _getRequestURI_ inside _UndertowLogbackAccessEvent_:
```java
@Override
    public String getRequestURI() {
        String requestUri = getAttribute("javax.servlet.error.request_uri");
        return requestUri != null ? requestUri : super.getRequestURI();
    }
```
