### ISSUE TITLE
Is there a plan to support SyslogAppender?

### ISSUE THREAD

**Issue by cuipengfei** [akkinoc/logback-access-spring-boot-starter#47]
I am trying to send access log to syslog.

But I am getting:

`ERROR in ch.qos.logback.classic.net.SyslogAppender[SYSLOG] - Appender [SYSLOG] failed to append. java.lang.ClassCastException: net.rakugakibox.spring.boot.logback.access.tomcat.TomcatLogbackAccessEvent cannot be cast to ch.qos.logback.classic.spi.ILoggingEvent`

**Comment by akihyro** [comment]
Logback is divided into three modules, logback-core, logback-classic and logback-access.
`ch.qos.logback.classic.net.SyslogAppender` is a class for classic logging (for `ILoggingEvent`).
Please use a class for access logging (for `IAccessEvent`).

Unfortunately, Logback-access's SyslogAppender does not seems to be provided at this time.
Please combine another libraries or your own implementation.

For your reference, I found a similar issue/pull-request in Logback-access:

* https://jira.qos.ch/browse/LOGBACK-1251
* https://github.com/qos-ch/logback/pull/355

Thanks.

**Comment by akkinoc** [comment]
This issue is inactive, so I close it.
If you still have problems, please open a new issue.
