### ISSUE TITLE
maybe make `spring-boot-starter-web` optional dependency

### ISSUE THREAD

**Issue by ckoutsouridis** [akkinoc/logback-access-spring-boot-starter#54]
At the moment this awesome starter has a dependency on `spring-boot-starter-web` which by default brings tomcat.

Would it make sense to make `spring-boot-starter-web` optional as it does with `spring-boot-starter-webflux` dependency?

**Comment by mangan77** [comment]
I second this. The library should be less opinionated about what to use.

**Comment by akkinoc** [comment]
Sorry for the late reply. Thanks for report!
`spring-boot-starter-web` has been made optional by PR # 49.
